name: .NET

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:    
      - uses: actions/checkout@v2
    
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
	
      - name: Install dependencies
        run: |
          dotnet restore
      
      - name: Build
        run: |
          cd ./src/Sample
          nuget pack MyPackage.1.0.0.nuspec -OutputDirectory ../../packages
      
      - name: Pack
        run: |
          dotnet pack MyGreatLib.csproj -o artifacts/

#      - uses: actions/upload-artifact@v1
#        with:
#          name: artifacts
#          path: artifacts

      - name: Publish to GitHub Packages
        run: |
          cd ../../packages
          dotnet nuget add source "https://nuget.pkg.github.com/maegawa-h/index.json" -n "github" -u maegawa-h -p ${{secrets.GH_PACKAGES_PAT}} --store-password-in-clear-text
          dotnet nuget push "*.nupkg" --api-key ${{secrets.GH_PACKAGES_PAT}} --source "github" --skip-duplicate
